# Generated by Django 4.2 on 2024-11-23 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='url',
        ),
        migrations.AddField(
            model_name='content',
            name='release_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='userhistory',
            name='rating',
            field=models.FloatField(default=5.0),
        ),
        migrations.AlterField(
            model_name='content',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='UserPreference',
        ),
    ]
